### ISSUE TITLE
👀 🙈 Show / Hide Password Button

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-password-strength-meter#11]
## Description
It would be nice to have a small icon / indicator to show & hide your password. 
Would be useful on mobile and for single-password signups, where you don't want to add a verification password field.

## Todo-list

- [x] Add `showPassword` prop to toggle password show and hide
- [x] Add `toggle` prop to toggle internal show / hide button
- [x] Add SVG Icon for password show and password hide
- [ ] ~~Add slot for icon / button so people can customize it~~
- [x] Emit `showPassword` and `hidePassword` event

**Comment by apertureless** [comment]
Implemented with https://github.com/apertureless/vue-password-strength-meter/commit/5fa79e1909e054c5136b21c74f070b2894db03d2
